### ISSUE TITLE
password prop passed to TextInput gets ignored by component

### ISSUE THREAD

**Issue by jariz** [ptmt/react-native-macos#188] opened 2018-03-08 11:00 UTC
### Description

The `TextField` var gets [declared](https://github.com/ptmt/react-native-macos/blob/master/Libraries/Components/TextInput/TextInput.js#L617), but the TextInput always uses [RCTTextView instead](https://github.com/ptmt/react-native-macos/blob/master/Libraries/Components/TextInput/TextInput.js#L619).
I'm not entirely sure how it's possible that this is not a problem for the UIExplorer app, however.
I can not get the text input to display as a secure text entry without modifying `TextInput` to use `TextField` over `RCTTextField`.

### Reproduction Steps and Sample Code

```jsx
<TextInput password />
```

### Solution

Use the `TextField` variable.
I can open a PR, I'm just wondering how it's possible that the UIExplorer does work.
Can you confirm if am I still doing something wrong somehow?

### Additional Information

* React Native version: 0.16.0(-alpha)
* Platform: MacOS...
* Development Operating System: MACOS!
* Dev tools: `(╯° °）╯︵ ┻━┻ `

**Comment by aleclarson** [comment] 2019-01-29 15:51
@jariz Password inputs are working in RNTester, so I'll need a sample repo with the exact setup you were using when you encountered this bug. If you can't reproduce with the latest version, let me know! Until then, I'm going to close this. ❤️

**Closed by aleclarson** 2019-01-29 15:51 UTC
Labels: invalid
