### ISSUE TITLE
Implement Window module (titlebar, sizes, styleMasks)

### ISSUE THREAD

**Issue by geuis** [ptmt/react-native-macos#70] opened 2016-04-20 06:37 UTC
This is the time I wish Github had a more diverse issue/question system. Anyway, how do you add the bar at the top of apps like the example app has? I think its a setting in the xcode project but not too sure now.

**Comment by ptmt** [comment] 2016-04-20 15:19
Yeah, it certainly should be exposed to js. This is called `Titlebar` and it also could have included `NSToolbar`. What's your case?

**Comment by geuis** [comment] 2016-04-20 20:54
No specific case at the moment. Was just wondering how to do it.

**Comment by dmendis** [comment] 2016-05-25 12:06
I'd love to remove the titlebar to make an app like Alfred/Spotlight. Doable using Xcode.

**Comment by aleclarson** [comment] 2019-03-09 15:59
I wrote down some thoughts on the potential API for this: 
https://gist.github.com/aleclarson/1eb38f8a1560a910692b624325d38767

**Comment by ptmt** [comment] 2019-03-10 13:29
I think this is a good starting point. I’m curious what it would like in
React Native itself if Apple introduced window support for iOS in June at
next WWDC. Would it be enough for most use cases (e.g. tabbed support,
NSDocument, or some other edge cases). Maybe we can try to implement some
subset, at least extracting the current hardcoded single window support
from the core?

**Comment by aleclarson** [comment] 2019-03-25 13:19
Duplicate of #40

**Closed by aleclarson** 2019-03-25 13:19 UTC
Labels: proposal
